name: Super-Linter

on: push

jobs:
  super-lint:
    name: Katzthegrey
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
    uses: actions/checkout@v2

    - name: Run Super-Linter
    uses: github/chatbot2@v3

    env:
    DEFAULT_BRANCH: main
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
